### PR TITLE
refactored, fixed bugs, updated readme

### PR DESCRIPTION
**Pull request by harshkpatel**
Moved packages around, fixed a bug with action space, made output strings more appealing and updated ReadME, Let me know if you guys want any changes.

### CODE REVIEW

**Comment by kRichard32** [comment]
I added a few more tests and moved some files around as well. As well, I fixed bugs in mortgage and unmortgage, and altered the saving use case to be more helpful to the user.

**Review by kRichard32 — APPROVED** [review]
Good choice on moving all the files into packages which represent their location in the clean architecture hierarchy. However, I will be moving the logic package into the UseCase package, as the Logic package really is just an assortment of UseCases.

**Comment by kRichard32** [comment]
Actually, the more that I think about it, I think the Logic package deserves its own place in the directory. Therefore, I've reverted my change of moving the logic folder inside the Usecases package

**Comment by kRichard32** [comment]
I had to force push a previous version of the branch because a merge from @derrcodes failed.

**Comment by benxu3** [comment]
Thanks for refactoring the code and adding tests. The changes to naming in the Logic directory look straightforward and intuitive to understand.

**Review by benxu3 — APPROVED** [review]

**Review by derrcodes — APPROVED** [review]
Great changes with the names and to the readme. Should be easier to understand now. Good job :)

**Pull request merged**
