### PR TITLE
Added jail perform action

### PR DESCRIPTION
**Pull request by Leuxll**
Added jail performAction so that now when a player is in the jail cell, they should now draw a card and perform a specific action.

### CODE REVIEW

**Review by kRichard32 — CHANGES_REQUESTED** [review]
On line 61, we might need to put an else statement.

**Review by harshkpatel — APPROVED** [review]
Since the else statement is fixed, everything looks good now

**Review by kRichard32 — APPROVED** [review]
With the new change, it seems to be good for merging!

**Review by susannah-c — APPROVED** [review]
The new changes look good, I think it's ready to be merged.

**Pull request merged**
