### PR TITLE
completed some tests for Player, edited the rollDice and buildHouse m…

### PR DESCRIPTION
**Pull request by Cindywwang**
…ethods, edited the javadoc for rollDice.

### CODE REVIEW

**Review by giaphuongd — COMMENTED** [review]
I don't think you've pushed any tests. Can you double check? Also, can you add a third reviewer in for the PR thanks :)

**Review by harshkpatel — COMMENTED** [review]
Overall good choices for change to the methods. The merge conflict is fixed, but it might cause issues with how roll dice is called in other classes as now it takes a parameter, and its likely that there will be refactoring needed for some of the code that are already in a PR, but not merged. Another comment is the changes to the .gitignore and various .xml files, as those changes seem extraneous, but I do not think they will pose a big issue. Besides those nitpicks, good choice of test suites, I think you covered most cases and I can't think of any glaring edge cases off the top of my head.

**Review by harshkpatel — APPROVED** [review]

**Review by kRichard32 — APPROVED** [review]
Good use of recursion in order to solve the problem. As well, the tests seem mostly encompassing, that is also a plus. It should be ready to merge once the conflicts are sorted out.

**Review by giaphuongd — APPROVED** [review]
Looks good! :)

**Review by kRichard32 — APPROVED** [review]
Once again, neat code, clear JavaDoc, and good encompassing tests. The merge conflicts have been resolved, so it should be able to merge once we get enough approval.

**Pull request merged**
