### PR TITLE
create Property class

### PR DESCRIPTION
**Pull request by benxu3**
Created Property class with instance variables and constructor. Fixed errors in Player class.

### CODE REVIEW

**Review by kRichard32 — APPROVED** [review]
We might have to add on to this later, but it looks good for now. All the instance attributes are nicely organized.

**Review by derrcodes — APPROVED** [review]
nice

**Comment by Leuxll** [comment]
LGTM!

**Review by Leuxll — COMMENTED** [review]
LGTM!

**Pull request merged**
