### PR TITLE
Iocleanup

### PR DESCRIPTION
**Pull request by harshkpatel**
Fixed Warnings with IO Objects

### CODE REVIEW

**Review by benxu3 — APPROVED** [review]
Thanks for adding tests and good work fixing the warnings

**Comment by harshkpatel** [comment]
> 

I don't know why the tests got merged into this branch but I do not think there will be any issues with merging

**Review by derrcodes — APPROVED** [review]
Good changes to remove warnings. I'll assume nothing is broken and I hope you checked cause GitHub is having issues checking stuff right now.

**Review by kRichard32 — APPROVED** [review]
Good fixes on the comments and Javadoc.

**Pull request merged**
