### PR TITLE
Actionspace

### PR DESCRIPTION
**Pull request by Leuxll**
Fixed the ActionSpace out of bound error, fixed other minor bugs, moved file to the correct spot and added more test cases.

### CODE REVIEW

**Review by harshkpatel — APPROVED** [review]
Nothing big to say, Good changes to make certain code more readable.

**Review by derrcodes — APPROVED** [review]
Not much to comment on all the changes are good and there is nothing too significant.

**Comment by benxu3** [comment]
Nice work finding and fixing the error.

**Review by benxu3 — APPROVED** [review]
Nice work finding and fixing the error.

**Pull request merged**
